"""
Run the Option 3 Step 1 feature importance audit across all six
(league, market) combinations.

Loads each league's pipeline once and reuses the full_df for all
markets of that league. Writes one CSV per combo to reports/.

Runtime: ~10-15 minutes total.
Run:     python scripts/run_feature_audit.py
         python scripts/run_feature_audit.py --league PL         # single league
         python scripts/run_feature_audit.py --market ou25       # single market
"""
from __future__ import annotations

import argparse
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd

from model import audit_features


COMBOS: list[tuple[str, str]] = [
    ("PL",  "ou25"),
    ("PL",  "btts"),
    ("EFL", "ou25"),
    ("EFL", "ou15"),
    ("EFL", "btts"),
]


def _load_league_pipeline(league: str) -> pd.DataFrame:
    """Load pipeline data for a league and return the full_df."""
    if league == "PL":
        from pipeline import run_pipeline as _pl_pipeline
        data = _pl_pipeline(verbose=True)
    elif league == "EFL":
        from championship_pipeline import run_pipeline as _efl_pipeline
        data = _efl_pipeline(verbose=True)
    else:
        raise ValueError(f"Unknown league: {league}")
    return data["full_df"].copy()


def _write_summary(results: dict[tuple[str, str], pd.DataFrame],
                   output_dir: str) -> None:
    """Write a synthesised one-page markdown summary covering all combos."""
    lines: list[str] = [
        "# Feature Audit Summary",
        "",
        "Auto-generated by `scripts/run_feature_audit.py`. "
        "See `feature_audit_{league}_{market}.csv` for full per-combo detail.",
        "",
    ]
    for (league, market), df in results.items():
        noise_row = df[df["feature"] == "__noise_baseline__"]
        if not noise_row.empty:
            noise_drop = float(noise_row["perm_auc_drop"].iloc[0])
        else:
            noise_drop = float("nan")

        pruning = df[df["pruning_candidate"] & (df["feature"] != "__noise_baseline__")]
        top10 = df.head(10)

        lines.append(f"## {league} / {market}")
        lines.append("")
        lines.append(
            f"- Features audited: {len(df) - 1} "
            f"(+ 1 noise baseline = {len(df)})")
        lines.append(f"- Noise baseline perm_auc_drop: `{noise_drop:+.5f}`")
        lines.append(f"- Pruning candidates (perm <= noise): **{len(pruning)}**")
        lines.append("")
        lines.append("### Top 10 contributors (by perm_auc_drop)")
        lines.append("")
        lines.append("| Rank | Feature | Group | perm_auc_drop | xgb_gain | nan_rate |")
        lines.append("|------|---------|-------|---------------|----------|----------|")
        for i, row in top10.iterrows():
            lines.append(
                f"| {i + 1} | `{row['feature']}` | {row['group']} | "
                f"`{row['perm_auc_drop']:+.5f}` | `{row['xgb_gain']:.4f}` | "
                f"`{row['nan_rate']:.2%}` |")
        lines.append("")

        if len(pruning) > 0:
            lines.append("### Pruning candidates (first 20)")
            lines.append("")
            lines.append("| Feature | Group | perm_auc_drop | nan_rate |")
            lines.append("|---------|-------|---------------|----------|")
            for _, row in pruning.head(20).iterrows():
                lines.append(
                    f"| `{row['feature']}` | {row['group']} | "
                    f"`{row['perm_auc_drop']:+.5f}` | `{row['nan_rate']:.2%}` |")
            if len(pruning) > 20:
                lines.append(
                    f"| … _{len(pruning) - 20} more rows_ | | | |")
            lines.append("")

        # Group-level summary (perm_auc_drop aggregated by group)
        group_summary = (
            df[df["feature"] != "__noise_baseline__"]
            .groupby("group")
            .agg(n=("feature", "size"),
                 mean_perm=("perm_auc_drop", "mean"),
                 max_perm=("perm_auc_drop", "max"),
                 pruning_candidates=("pruning_candidate", "sum"))
            .sort_values("mean_perm", ascending=False)
            .reset_index()
        )
        lines.append("### Group-level summary")
        lines.append("")
        lines.append("| Group | n | mean perm | max perm | # pruning cand. |")
        lines.append("|-------|---|-----------|----------|-----------------|")
        for _, row in group_summary.iterrows():
            lines.append(
                f"| {row['group']} | {row['n']} | "
                f"`{row['mean_perm']:+.5f}` | `{row['max_perm']:+.5f}` | "
                f"{row['pruning_candidates']} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    out_path = os.path.join(output_dir, "feature_audit_summary.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\n[summary] wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Run Option 3 feature audit")
    parser.add_argument("--league", type=str, default=None,
                        help="Restrict to a single league (PL or EFL)")
    parser.add_argument("--market", type=str, default=None,
                        help="Restrict to a single market (ou25, ou15, btts)")
    parser.add_argument("--output-dir", type=str, default="reports",
                        help="Directory for audit output files")
    args = parser.parse_args()

    filtered_combos = [
        (l, m) for (l, m) in COMBOS
        if (args.league is None or l == args.league.upper())
        and (args.market is None or m == args.market.lower())
    ]
    if not filtered_combos:
        print("No combos match the filter - nothing to do")
        return

    print(f"\n{'#' * 70}")
    print(f"#  Feature audit runner - {len(filtered_combos)} combos")
    print(f"{'#' * 70}\n")

    # Cache pipeline per league
    league_cache: dict[str, pd.DataFrame] = {}
    results: dict[tuple[str, str], pd.DataFrame] = {}

    for (league, market) in filtered_combos:
        if league not in league_cache:
            print(f"\n[pipeline] Loading {league} data...")
            league_cache[league] = _load_league_pipeline(league)
            print(f"[pipeline] {league}: {len(league_cache[league])} rows")

        print(f"\n{'=' * 70}")
        print(f"  Auditing {league} / {market}")
        print(f"{'=' * 70}")

        df = audit_features(
            league=league,
            market=market,
            full_df=league_cache[league],
            output_dir=args.output_dir,
            verbose=True,
        )
        results[(league, market)] = df

    if len(results) > 1:
        _write_summary(results, args.output_dir)

    print(f"\n{'#' * 70}")
    print(f"#  Feature audit complete - wrote {len(results)} CSV(s) "
          f"to {args.output_dir}/")
    print(f"{'#' * 70}\n")


if __name__ == "__main__":
    main()
